---

- name: manage httpd.conf
  hosts: webservers
  become: yes
  tasks:
  - name: Copy Apache configuration file
    copy:
     src: httpd.conf
     dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart service 
  handlers: 
  - name: restart service  
    systemd:
     name: httpd
     state: restarted
