---
- name: test template
  hosts: webservers
  gather_facts: yes
  become: yes
  tasks:
  - name: deploy index.html
    template:    
     src: templates/index.html.j2
     dest: /var/www/html/index.html
     mode: 0644
