---

- name: create users from vars
  hosts: webservers
  become: yes
  vars_files:
  - vars/users.yml
  tasks:
  - name: user created
    user:
     name: "{{user}}"
     group: "{{group}}"
     home: "{{homedir}}"
     shell: "{{shell}}"
