---

- name: create users from vars
  hosts: webservers
  become: yes
  vars:
   user: admin
   group: wheel
   homedir: /dev/null
   shell: /bin/false
  tasks:
  - name: user created
    user:
     name: "{{user}}"
     group: "{{group}}"
     home: "{{homedir}}"
     shell: "{{shell}}"
